[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports_ignore = ["test", "script"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout", "metadata", "evm.deployedBytecode.object"]

solc = "0.8.35"
optimizer = true
optimizer_runs = 10000

remappings = [
    "@forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@era-contracts/=lib/mock-era-contracts/src/system-contracts/contracts/"
]

# foundry-devops
fs_permissions = [
  { access = "read", path = "./broadcast" },
  { access = "read-write", path = "./deployment" },
]

[fmt]
ignore=["lib/**"]
tab_width = 4
line_length = 120
bracket_spacing = true
int_types = "long"
quote_style = "double"
wrap_comments = true
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config